version: "3"


services:
  googlecomments:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure
    build: .
    ports:
    - 3001:3001
    
